name: Test backend

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test-backend:
    runs-on: ubuntu-20.04

    strategy:
      matrix:
        node: [18, 20]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2

      - name: Use Node.js ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: pnpm

      - run: sudo add-apt-repository -y ppa:qbittorrent-team/qbittorrent-stable
      - run: sudo add-apt-repository -y ppa:transmissionbt/ppa
      - run: sudo apt-get install -y qbittorrent-nox transmission-daemon

      - run: |
          wget https://github.com/jesec/rtorrent/releases/latest/download/rtorrent-linux-amd64.deb
          sudo dpkg -i rtorrent-linux-amd64.deb

      - run: pnpm i
      - run: pnpm test || pnpm test || pnpm test

      - uses: codecov/codecov-action@v3
        if: matrix.node == 18

      - run: |
          sudo apt-get remove --purge -y rtorrent
          sudo apt-get install -y rtorrent

      - run: pnpm run test --selectProjects rtorrent || pnpm run test --selectProjects rtorrent || pnpm run test --selectProjects rtorrent
        if: matrix.node == 18
